---
title: "NGS uppföljningsanalys"
format: pdf
geometry: "margin=1.5cm"
documentclass: "extarticle"
papersize: "a4"
fontsize: "8pt"
output:
  pdf_document:
    extra_dependencies: ["float"]
    includes:
      in_header: "footer_config.tex"
editor_options:
  chunk_output_type: console
params:
  variant_df: null
  annot_df: null
---

```{r param_check, echo=FALSE}
if (is.null(params$variant_df)) {
  stop("missing data frame parameter")
}
```

```{r setup, echo=FALSE}
knitr::opts_chunk$set(fig.align = "center", echo = FALSE)
```

```{r packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(here)
```

```{r build_plot}
d2 <- params$variant_df %>%
  filter(!is.na(Bedömning), Bedömning != "benign",  Bedömning != "sannolikt benign") %>%
  arrange(name, Provtagningsdag) %>%
  mutate(variant_code = LETTERS[as.integer(factor(name))],
         mod_vaf = ifelse(Bedömning == "ej påvisad", 0, VAF)) %>%
  group_by(name) %>%
  mutate(sample_point = str_c(variant_code, seq_along(name)))

facet_label_df <- d2 %>%
  select(name) %>%
  distinct() %>%
  mutate(Provtagningsdag = min(d2$Provtagningsdag))

if (is.null(params$annot_df)) {
  annotation_df <- tibble(Provtagningsdag = c(), label = c())
} else {
  annotation_df <- params$annot_df
}

sampling_dates <- tibble(
  x = unique(c(annotation_df$Provtagningsdag, d2$Provtagningsdag)),
  y = 0,
  type = rep(
    c("annotation", "sampling"),
    c(
      length(unique(annotation_df$Provtagningsdag)),
      length(unique(d2$Provtagningsdag))
    )
  )
)

vaf_plot <- ggplot(d2, aes(Provtagningsdag, VAF, colour = name, fill = name)) +
  facet_wrap(vars(name), ncol = 1) +
  geom_vline(
    data = sampling_dates,
    mapping = aes(xintercept = x, linetype = type),
    colour = "gray"
  ) +
  geom_line(linewidth = 1) +
  geom_area(alpha = 0.3) +
  geom_point(data = d2 %>% filter(!is.na(Bedömning), Bedömning != "ej påvisad"), size = 3) +
  ggrepel::geom_text_repel(
    aes(label = round(100 * mod_vaf, digits = 1)),
    hjust = 2, vjust = 0.5, fontface = "bold",
    colour = "black", box.padding = 0.25) +
  scale_colour_discrete(name = "Variant") +
  scale_fill_discrete(name = "Variant") +
  scale_linetype_manual(values = c(annotation = "dashed", sampling = "solid")) +
  scale_x_datetime(date_labels = "%Y-%m-%d",
                   breaks = sampling_dates$x,
                   guide=guide_axis(n.dodge = 2),
                   sec.axis = sec_axis(~ .,
                                       breaks = unique(annotation_df$Provtagningsdag),
                                       labels = annotation_df$label)) +
  scale_y_continuous(labels = scales::label_percent(),
                     limits = c(0, max(0.5, max(d2$VAF)))) +
  labs(y = "VAF (%)") +
  theme_bw() +
  theme(
    axis.title.x.bottom = element_blank(),
    axis.text.x.bottom = element_blank(),
    axis.text.x.top = element_text(angle = -30, hjust = 1, face = "bold", size = 12),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    plot.margin = margin(b = 0),
    legend.key.width = unit(2, "cm"),
    strip.text = element_text(hjust = 0, face = "bold", size = 12),
    strip.background = element_rect(colour = "black", fill = "#EEEEEE"),
    legend.position = "none"
  )
```

```{r x_axis_labels}
x_axis_labels <- ggplot(sampling_dates, aes(x = x, y = y)) +
  ggrepel::geom_text_repel(aes(label=format(x)),
    box.padding = 0.4,
    direction = "both",
    force_pull = 1,
    segment.colour = "gray",
    nudge_y = -0.5,
    size = 3.5) +
  scale_x_datetime() +
  scale_y_continuous(limits = c(-1, 0), expand = expansion(mult = 0, add = 0)) +
  labs(x = "Provtagningsdag") +
  theme_void() +
  theme(
    axis.title.x = element_text(size = 11),
    plot.margin = margin(t = 0)
  )
```

```{r build_table}
vaf_table <- d2 %>% ungroup() %>%
  select(Provtagningsdag, Provnr, Material, Symbol, HGVSc, HGVSp, mod_vaf, Sekvensdjup, Kommentar) %>%
  mutate(id_material = str_c(Provnr, str_replace_na(Material, ""), sep = " "),
         Kommentar = ifelse(is.na(Kommentar), "", Kommentar),
         mod_vaf = 100 * mod_vaf,
         HGVS = str_c(HGVSc, HGVSp, sep = ", ")) %>%
  arrange(Provtagningsdag) %>%
  select(Provtagningsdag, id_material, Symbol, HGVS, mod_vaf, Sekvensdjup, Kommentar) %>%
  rename(Provnr = id_material, `VAF (%)` = mod_vaf)
```

```{r output_plotr, fig.width = 10, fig.height = 12.5, warning = FALSE, message = FALSE, fig.pos = "H"}
library(patchwork)
vaf_plot / x_axis_labels + plot_layout(heights = c(0.92, 0.08))
```

\newpage

```{r output_table, results = "asis"}
print(kableExtra::kbl(vaf_table,
                      align = "llllrrl",
                      digits = 1,
                      format = "latex",
                      booktabs = TRUE,
                      longtable = TRUE,
                      escape = TRUE,
                      row.names = FALSE) %>%
        kableExtra::column_spec(2, width = "1.5cm") %>%
        kableExtra::column_spec(4, width = "4.5cm") %>%
        kableExtra::column_spec(7, width = "4cm") %>%
        kableExtra::collapse_rows(columns = c(1, 2), valign = "middle", latex_hline = "major") %>%
        kableExtra::kable_classic_2(latex_options = c("repeat_header")))
```
